### ISSUE TITLE
RFC: Project code structure refactoring

### ISSUE THREAD

**Issue by OlegJakushkin** [kiliakis/BLonD-minimal-cpp#14]
It is note user, nor developer friendly.
One can look at current tests and [see](https://github.com/kiliakis/BLonD-minimal-cpp/blob/ae572d61d56c93e51fb66d2cfb56b6c3905dcc9b/unit-tests/testResonator.cpp) lots of scarry C++ code with refrences to folder structure and such 

```cpp
#include "globals.h"
#include "utilities.h"
#include "math_functions.h"
#include <omp.h>
#include <stdio.h>
#include "../input_parameters/GeneralParameters.h"
#include "../input_parameters/RfParameters.h"
#include "../beams/Beams.h"
#include "../beams/Slices.h"
#include "../beams/Distributions.h"
#include "../trackers/Tracker.h"
#include "../impedances/Intensity.h"
#include <gtest/gtest.h>
```

Also one can look onto demo applications and see [similar picture](https://github.com/kiliakis/BLonD-minimal-cpp/blob/ae572d61d56c93e51fb66d2cfb56b6c3905dcc9b/tests/LHC_restart.cpp):

```cpp
#include "globals.h"
#include "utilities.h"
#include "math_functions.h"
#include <omp.h>
#include <stdio.h>
#include "../input_parameters/GeneralParameters.h"
#include "../input_parameters/RfParameters.h"
#include "../beams/Beams.h"
#include "../beams/Slices.h"
#include "../beams/Distributions.h"
#include "../trackers/Tracker.h"
#include "../llrf/PhaseLoop.h"
#include "optionparser.h"
```

Something shall be done with it.

**Comment by OlegJakushkin** [comment]
First we shall separate source into `src` and include into `include` folders. Rename refrences.There is a prototype of such architecture in [here](https://github.com/OlegJakushkin/BLonD-minimal-cpp/tree/380e375f130a0e7b1dae77361a1320d41fb0f54f)

There are 2 good reasons to use additional `include/blond/` folder to encapsulate all the blond code files structure:
- If one would like to include blond in other projects (use it like a real library in a moderate size project) without `blond` subfolder conflicts will emerge with other libraries - `global.h` and other file names are common. 
- One can find that such nesting is a best practice in projects like boost, tbb, and all other libraries in C++ world.

**Q**: What happens If we do with out folder anyway?
**A**: The only big libraries that do not use such nesting I know is CERN Root and Qt, yet they name all files starting with `T` or `qt` so one would need to select one ugly letter like "b" and attach it to each header file in hopes that no one has done it before us, nstead of nice and readable "blond" name.

So I heavily suggest to follow "Express ideas directly in code" C++ core [guideline ](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#p1-express-ideas-directly-in-code)and keep all blond include files in OO manner in one folder.

**Q**: What can we do to make new developers use something simpler than read the documentation and find what blond files to include? (you can look at any current test files to see that there is something wrong with 10 lines of includes):
**A**: We can introduce `#include <blond.h>` that would be one include that library clients would ever need to use all of the blond features. It can exist inside blond subfolder for consistancy, yet it is not required.

This is currently an RFC so please do comment what do you think.

**Comment by kiliakis** [comment]
The new project code structure has been introduced
