### ISSUE TITLE
Optimisation flags for gcc

### ISSUE THREAD

**Issue by dpiparo** [kiliakis/BLonD-minimal-cpp#18]
Hi,

I only have a mac presently at disposal. Given that the config has some glitches on osx, I am not able to check this myself but it seems to me, and perhaps I am wrong, that the optimisation flags for gcc are not set correctly and the implicit "-O0" is used.

Cheers,
     Danilo

**Comment by OlegJakushkin** [comment]
The [-O0](https://gcc.gnu.org/onlinedocs/gnat_ugn/Optimization-Levels.html) option is set only for [Debug configuration](https://github.com/kiliakis/BLonD-minimal-cpp/blob/850bf5e203d0d702f84f47940e721b2b71148040/CMakeLists.txt#L88). Release is currently using default Cmake configuration for GCC Release. Probably better to specify `set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -Ofast")` between this lines [111-112](https://github.com/kiliakis/BLonD-minimal-cpp/blob/850bf5e203d0d702f84f47940e721b2b71148040/CMakeLists.txt#L111-L112)

**Comment by dpiparo** [comment]
Hi Oleg,

right. For Clang Ofast is specified. I would recommend to do the same for gcc :)

Cheers,
     Danilo
