### ISSUE TITLE
Setup a TravisCI instance to manage building and testing 

### ISSUE THREAD

**Issue by kiliakis** [kiliakis/BLonD-minimal-cpp#6]
As performance is always one of our main concerns, except from unit and integration tests, some valgrind memchecks could be very helpful.

**Comment by OlegJakushkin** [comment]
CI integration file created. [Pull request created](https://github.com/kiliakis/BLonD-minimal-cpp/pull/8) #8  for you to accept (and configure Travis for this repository).

Tests require some absent configuration. Please provide details on how they shall be executed? 

![image](https://cloud.githubusercontent.com/assets/2915361/15002756/5dd01494-11ad-11e6-89c0-7ad193d93592.png)

**Comment by kiliakis** [comment]
The problem is that tests are not generated at all. If you look inside CMakeListst.txt there is an optional requirement of having installed Google Test: find_package(GTest). If true, variable GTest_FOUND is set true as well. So later in the CMakeLists.txt, tests are compiled only GTest_FOUND==true. I think that the problem will be resolved if GTest is properly installed. 
About the TravisCI instance, we'll have to figure out how to install gtest there..

**Comment by kiliakis** [comment]
@OlegJakushkin  Although building and testing works fine, no info about the outcome of the tests is displayed. It would be very helpful to separate building from testing and display info for both.

**Comment by OlegJakushkin** [comment]
Added #10 with coveralls service support, verbose unit-tests during builds. Pull in and update service refrences with your account.

![image](https://cloud.githubusercontent.com/assets/2915361/15098282/1149e986-1542-11e6-92a5-8fb6b9751fd6.png)
![image](https://cloud.githubusercontent.com/assets/2915361/15098283/1efdbf12-1542-11e6-9b87-90865d792041.png)
![image](https://cloud.githubusercontent.com/assets/2915361/15098289/40a74a3e-1542-11e6-8a57-b2b46635117c.png)

Cant get any more detailed now.=)

**Comment by kiliakis** [comment]
Nice job @OlegJakushkin  :)
I'll close this
